name: CD Pipeline 

on:
  push:
    branches:
      - main  # Trigger this pipeline on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 4: SSH into the EC2 instance to deploy the application
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # GitHub Secret for EC2 public IP
          username: ubuntu  # Assuming you are using the default Ubuntu user for EC2
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secret for SSH private key
          script: |
            # Update package index and install dependencies
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # Add Docker's official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    
            # Install Docker
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    
            # Install Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
    
            # Verify installations
            docker --version
            docker-compose --version
    
            # Clone the project repository to the EC2 instance
            cd /home/ubuntu/
            if [ ! -d "fastapi-book-project" ]; then
              git clone https://github.com/odero-lavenda/fastapi-book-project.git
            else
              cd fastapi-book-project
              git pull origin main  # Pull latest changes from the main branch
      
            # Navigate to the project folder and build/restart Docker containers
            cd /home/ubuntu/fastapi-book-project/
            sudo docker-compose up -d --build # Rebuild and start containers in detached mode